### ISSUE TITLE
projL1Inf.c file

### ISSUE THREAD

**Issue by jlherraiz** [doksa/altginv#1]
Hi, my name is Joaquin L. Herraiz. First of all, thank you for sharing the code and for the 2-detailed papers on Arxiv. 

I´m having problems with the projL1Inf.c file. It is just the C-code, so it cannot be directly compiled with mex (i.e. mex -O projL1Inf.c) . I adapted it (creating the mexFunction) but it seems that the number of parameters and its order is different than the one in the .m code (For instance when it is called from prox_l1l1.m with only 3 parameters). I can spend some time to solve it, but maybe there is an updated version of the .c code prepared for mex compilation.

Thanks,

**Comment by doksa** [comment]
Hi Joaquin,

Sorry for the late response—I'm on vacation right now so I'm sloppy with
e-mail. Thanks for catching this. I pushed the mex wrapper (written by the
authors of the corresponding paper).

Hope this helps,
Ivan

**Comment by jlherraiz** [comment]
Thanks, Ivan!
That worked.
Just in case, in the README, you can now add how to compile it:  
 mex mex-projL1Inf.c -output projL1Inf

Best,
Joaquin
